### ISSUE TITLE
user profile example

### ISSUE THREAD

**Issue by ouhouhsami** [sorl/django-mockups#3]
hello, 

I'm trying to generate UserProfile instances with

```
    profiles = Mockup(UserProfile)
    profiles.create(100)
```

, but each time, I get 
CreateInstanceError: Cannot solve constraints for "my_app.UserProfile", tried 1000 times. Please check value generators or model constraints. At least the following fields are involved: user
I have got a foreignkey with unique = True on UserProfile to django User model (auth.User)

any ideas ?

**Comment by sorl** [comment]
probably not a bug
